
name: magic8ball # check to see if it's available
version: '2.0.0+git' # this is freakin' awesome
summary: Ask the Magic 8-ball. # 79 char long summary
description: |
  Learn your fortune and get advice from the Magic 8-ball! 
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs

apps:
  magic8ball:
    command: magic8ball
    plugs:
      - home
     
parts: 
  my-part:
    source: https://github.com/kz6fittycent/magic8ball
    source-type: git
    plugin: python3
    
    build-packages:
      - python3
      
    stage-packages:
      - python3
  
